version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333
    networks:
      - rag-app-network
  
  qdrant:
    image: "qdrant/qdrant:v1.12.0"
    ports:
      - "6340:6333"
      - "6341:6334"
    volumes:
      - ./backend/data/qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__ON_DISK_PAYLOAD: 'true'
    networks:
      - rag-app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/6333 && echo -e 'GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 180s
      retries: 3
      start_period: 40s

  streamlit:
    build:
      context: ./backend
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - rag-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_BACKEND_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_API_URL=http://backend:8000
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    #   - /app/.next
    networks:
      - rag-app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rag-app-network:
    driver: bridge